# Generated by Django 5.2.10 on 2026-06-19 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=100)),
                ('crowd_count', models.IntegerField()),
                ('wait_time', models.FloatField()),
                ('crowd_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(default='admin', max_length=100)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presentation Config',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('place_type', models.CharField(choices=[('hospital', 'Hospital'), ('mall', 'Mall'), ('bank', 'Bank'), ('government', 'Government Office'), ('other', 'Other')], default='other', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QueueBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_id', models.CharField(default='entrance-1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='queueai.place')),
            ],
            options={
                'unique_together': {('place', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_factor', models.FloatField()),
                ('actual_count', models.IntegerField()),
                ('raw_count', models.IntegerField()),
                ('calibrated_at', models.DateTimeField(auto_now_add=True)),
                ('calibrated_by', models.CharField(default='admin', max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='queueai.queueblock')),
            ],
            options={
                'ordering': ['-calibrated_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_count', models.IntegerField(default=0)),
                ('wait_time_min', models.FloatField(default=0.0, help_text='Wait time in minutes')),
                ('crowd_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('source', models.CharField(choices=[('sensor', 'WiFi Sensor'), ('manual', 'Admin Manual'), ('ml', 'ML Prediction')], default='sensor', max_length=20)),
                ('raw_device_count', models.IntegerField(default=0, help_text='Raw WiFi probe count before calibration')),
                ('calibration_factor', models.FloatField(default=1.0)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='queueai.queueblock')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['block', '-timestamp'], name='queueai_que_block_i_27a7f8_idx')],
            },
        ),
    ]
